a_k: 10
data_name: tree1
adata_file: ./data/tree1/data.h5ad
threshold: 0.2
adj_weight: 0.5
c: 0
clu_model: kmeans
learned_graph: CMI
device: cuda
dropedge_rate: 0.5
dropout: 0.5
einterval: 1
epochs: 100
exp_out: 512
filter_cell: 3
gamma: 3
grn_batch_size: 64
grn_out: 256
hidden_dim: 256
hvg: false
input_dim: 256
k: 10
lr: 0.0001
margin: 0
margin_weight: 1.5
maskfeat_rate_anchor: 0.0
maskfeat_rate_learner: 0.0
nlayers: 2
no_bn: false
norm_target: null
ntrials: 5
proj_dim: 64
refine: 50
rep_dim: 64
sim_weight: 0.5
species: Mouse
tau: 0.999
temperature: 0.2
w_decay: 0.001
percent: 0.1
theshold: 0.3
root: sA
clu_dir: ./clu_result/tree1/CMI/
output_dir: ./result/tree1
CMI_dir: ./cmi_result/tree1/CASCAT/10/
img_dir: ./img/
emb_path: ./clu_result/2024-05-16_04-25-13/trial4_ARI0.71682.npy
job_dir: ./clu_result/2024-05-16_04-25-13/